import type { Destination } from "./types";

export const sampleDestinations: Destination[] = [
  {
    cityId: "fukuoka_japan",
    cityName: "후쿠오카",
    country: "일본",
    region: "East Asia",
    mainAirport: "FUK",
    timezone: "Asia/Tokyo",
    shortIntroKo: "짧은 일정과 음식·쇼핑 여행에 강한 일본 도시입니다.",
    keywordsKo: ["맛집", "쇼핑", "짧은비행", "가성비"],
    recommendedNights: {
      min: 2,
      ideal: 3,
      max: 5,
    },
    seasons: {
      bestMonths: [3, 4, 5, 10, 11],
      cautionMonths: [7, 8],
    },
    climateByMonth: {
      7: {
        avgTempC: 28,
        rainfallMm: 250,
        climateNote: "덥고 습하며 비가 많은 편입니다.",
      },
    },
    costProfile: {
      flightCostRangeFromICN: [250000, 400000],
      hotelPerNightRange: [70000, 120000],
      dailyLocalCostRange: [70000, 120000],
      currency: "KRW",
      note: "성수기에는 항공권 가격 변동이 큽니다.",
    },
    styleScores: {
      budget: 4,
      food: 5,
      shopping: 4,
      nature: 3,
      culture: 4,
      activity: 2,
      relaxed: 3,
      photo: 4,
      localExperience: 4,
    },
    companionScores: {
      solo: 4,
      couple: 4,
      friends: 5,
      family: 4,
      parents: 3,
    },
    landmarks: ["오호리공원", "캐널시티", "다자이후", "모모치해변"],
    dataQuality: {
      status: "draft",
      needsReview: true,
    },
  },
  {
    cityId: "danang_vietnam",
    cityName: "다낭",
    country: "베트남",
    region: "Southeast Asia",
    mainAirport: "DAD",
    timezone: "Asia/Ho_Chi_Minh",
    shortIntroKo: "휴양과 가성비에 강하지만 계절과 항공권 가격 변수가 있는 도시입니다.",
    keywordsKo: ["휴양", "바다", "가성비", "리조트"],
    recommendedNights: {
      min: 3,
      ideal: 4,
      max: 6,
    },
    seasons: {
      bestMonths: [2, 3, 4, 5],
      cautionMonths: [9, 10, 11],
    },
    climateByMonth: {
      9: {
        avgTempC: 28,
        rainfallMm: 300,
        climateNote: "우기 영향으로 비가 많을 수 있습니다.",
      },
    },
    costProfile: {
      flightCostRangeFromICN: [350000, 650000],
      hotelPerNightRange: [60000, 150000],
      dailyLocalCostRange: [50000, 100000],
      currency: "KRW",
      note: "항공권 가격에 따라 총비용 차이가 큽니다.",
    },
    styleScores: {
      budget: 5,
      food: 4,
      shopping: 2,
      nature: 4,
      culture: 3,
      activity: 3,
      relaxed: 5,
      photo: 4,
      localExperience: 3,
    },
    companionScores: {
      solo: 3,
      couple: 5,
      friends: 4,
      family: 4,
      parents: 4,
    },
    landmarks: ["미케비치", "바나힐", "한시장", "호이안"],
    dataQuality: {
      status: "draft",
      needsReview: true,
    },
  },
  {
    cityId: "paris_france",
    cityName: "파리",
    country: "프랑스",
    region: "Europe",
    mainAirport: "CDG",
    timezone: "Europe/Paris",
    shortIntroKo: "문화·예술·관광 매력은 높지만 짧은 일정과 낮은 예산에는 부담이 큰 도시입니다.",
    keywordsKo: ["문화", "예술", "관광", "장거리", "비싼물가"],
    recommendedNights: {
      min: 4,
      ideal: 5,
      max: 7,
    },
    seasons: {
      bestMonths: [4, 5, 6, 9, 10],
      cautionMonths: [7, 8, 12],
    },
    climateByMonth: {
      12: {
        avgTempC: 6,
        rainfallMm: 60,
        climateNote: "춥고 해가 짧은 편입니다.",
      },
    },
    costProfile: {
      flightCostRangeFromICN: [900000, 1600000],
      hotelPerNightRange: [160000, 320000],
      dailyLocalCostRange: [120000, 220000],
      currency: "KRW",
      note: "숙박비와 항공권 모두 예산 부담이 큰 편입니다.",
    },
    styleScores: {
      budget: 1,
      food: 4,
      shopping: 4,
      nature: 2,
      culture: 5,
      activity: 3,
      relaxed: 2,
      photo: 5,
      localExperience: 4,
    },
    companionScores: {
      solo: 4,
      couple: 5,
      friends: 4,
      family: 3,
      parents: 3,
    },
    landmarks: ["에펠탑", "루브르 박물관", "몽마르트르", "센강"],
    dataQuality: {
      status: "draft",
      needsReview: true,
    },
  },
];
